### PR TITLE
Update all `pacta.pkgdown.template` references

### PR DESCRIPTION
**Pull request by jdhoffa**
Relates to https://github.com/RMI-PACTA/pacta.pkgdown.rmitemplate/issues/15

### CODE REVIEW

**Review by AlexAxthelm — DISMISSED** [review]

**Comment by cjyetman** [comment]
Don't we have to update the DESCRIPTION file too?
https://github.com/RMI-PACTA/pactaverse/blob/297aecb88c7d7bad6f59711d2cc108259f69d797/DESCRIPTION#L69

**Comment by jdhoffa** [comment]
The scope of this PR has been expanded. Updating the references across all names.

**Comment by jdhoffa** [comment]
@cjyetman I would actually expect this `pkgdown` action to fail at this stage, since what is on `main` doesn't reflect the new name of this package. 

I imagine merging this will also handle https://github.com/RMI-PACTA/pacta.pkgdown.rmitemplate/issues/15#issuecomment-1918793090

**Comment by cjyetman** [comment]
> @cjyetman I would actually expect this `pkgdown` action to fail at this stage, since what is on `main` doesn't reflect the new name of this package.
> 
> I imagine merging this will also handle [#15 (comment)](https://github.com/RMI-PACTA/pacta.pkgdown.rmitemplate/issues/15#issuecomment-1918793090)

How I understand it, the pkgdown GH actions do try to build the site on a PR branch, but they do not deploy (actually push to GH pages), so I would not expect them to fail (unless something is legit wrong and it would not be able to build when pushed to main).

The error I'm getting in my PRs suggests that the template package is not findable (yet?)
> Caused by error:
> ! Could not solve package dependencies:
> 
> deps::.: Can't install dependency rmi-pacta/pacta.pkgdown.rmitemplate
> local::.: Can't install dependency rmi-pacta/pacta.pkgdown.rmitemplate

**Comment by jdhoffa** [comment]
That is what I am suggesting. The `main` branch of `rmi-pacta/pacta.pkgdown.rmitemplate` doesn't yet have an updated `DESCRIPTION` file, highlighting the updated package name. So when we try to install it in other actions, it can't find the package. 

This PR should fix that.

**Review by cjyetman — APPROVED** [review]

**Comment by cjyetman** [comment]
sweet! that seems to have fixed it. rerunning pkgdown action in my PRs completes successfully now

**Comment by jdhoffa** [comment]
Yay

**Comment by jdhoffa** [comment]
New best practice: 
Fix things and then break them and then fix them again! And rename EVERYTHING ALWAYS

**Pull request merged**
